### ISSUE TITLE
Mod replaces custom installation names with version strings.

### ISSUE THREAD

**Issue by Kichura** [LoganDark/fabric-branding#1]
When using any custom installation names such as "Walrus", The installation string gets replaced as "1.16.3" instead.
Basically meaning it is impossible to use your own installation names with this mod installed.

How to reproduce:

1: Create a fabric-based client using any name you want. (Jar and json must be renamed aswell)
2: Install this mod and create a new installation from launcher with game directory pointed to it.
3: Join any Realm/Multiplayer/Singleplayer world.
4: Press F3 and read the branding name via top-left.

**Comment by LoganDark** [comment]
I did that to remove the "MultiMC" installation name, so it's intended. If you want, I could specifically detect "Fabric"/"MultiMC" instead of using the Minecraft version every time.

**Comment by LoganDark** [comment]
In fact I even specifically left code commented out in the case someone came to me with a bug report like this:

https://github.com/LoganDark/fabric-branding/blob/6b682db8abde5d5a9e3d3ec85ddeb333511d649f/src/main/java/net/logandark/branding/mixin/MixinMinecraftClient.java#L41-L47

**Comment by Kichura** [comment]
^ Tried this method and it resolves the issue above, Thanks for your help.

**Comment by LoganDark** [comment]
@Kichura I kind of meant that it would be easy for me to resolve the issue for you, but if you'd prefer to keep a fork that's fine too.

**Comment by Kichura** [comment]
^ Forgot to reply to this comment above: Added the mod to my modpack & gave out credits.
