### ISSUE TITLE
Mod is incompatible with 1.17.x

### ISSUE THREAD

**Issue by Kichura** [LoganDark/fabric-branding#2]
When attempting to use this mod in 1.17.x, the game just crashes since the java code is entirely different.

**Comment by Romvnly-Gaming** [comment]
no commits in 10 months... I sense a fork is on it's way to save the day

**Comment by LoganDark** [comment]
> no commits in 10 months... I sense a fork is on it's way to save the day

Sorry, I'm currently tied up in other projects and can't work on this at the moment. Feel free to open a pull request if you'd like to update the mod.

**Comment by Kichura** [comment]
> 
> 
> > no commits in 10 months... I sense a fork is on it's way to save the day
> 
> Sorry, I'm currently tied up in other projects and can't work on this at the moment. Feel free to open a pull request if you'd like to update the mod.

Take your time as much as you need since not everything can be updated as fast as possible. Although i do agree that forks can sometimes help very well in specific cases like this one.

**Comment by xcodian** [comment]
+1 I'd greatly appreciate if you could bump the version up to 1.17.x

**Comment by BasicFisher** [comment]
+1. I would really appreciate if you could update this mod for 1.17.x when you find time.

**Comment by DimiDimit** [comment]
FYI, [IMS212's fork](https://github.com/IMS212/fabric-branding) seems to work fine.

**Comment by Kichura** [comment]
> 
> 
> FYI, [IMS212's fork](https://github.com/IMS212/fabric-branding) seems to work fine.

This comment has resolved my issue.
