### ISSUE TITLE
[NOT BUG] I Have a Question

### ISSUE THREAD

**Issue by fooeyround** [LoganDark/fabric-branding#4]
in The __ Mixin you use __ and I was Just Wondering Where your Tring to refer to, because it seems like this is no longer there. you say its "Is Modded" lambda in addSystemDetailsToCrashReport, I cant seem to find this method in my decompiled code, I cant Find it in MinecraftClient, so Any help about where you found it would be great, I see its for Crash Reports? does it effect server because it seems like it does not. Hope to get a reply.

**Comment by LoganDark** [comment]
> I cant seem to find this method in my decompiled code

Which method are you looking for? addSystemDetailsToCrashReport? Keep in mind that this mod is for 1.16

**Comment by fooeyround** [comment]
Yeah Seems like a lot has changed with this part of the code, I just mean you set it to method_1509 and I think 1509 got changed and I see its for getting signers, do you know what it was called in the decompiled Yarn? cause I Found Crashreport and Systedetails and Just asking if you know a yarn name for the class? or is it not renamed?

**Comment by fooeyround** [comment]
Okay So I found some of it.

**Comment by LoganDark** [comment]
It's not renamed because it's a lambda expression. 

addSystemDetailsToCrashReport contains a lambda expression that gets the signers of the jar file - I'm injecting into that lambda expression, which is not named because it doesn't show up in the mapping utility (forgot what it's called).

**Comment by fooeyround** [comment]
oh Yeah I see more now thx.

**Comment by fooeyround** [comment]
thx I think I found it.

**Comment by fooeyround** [comment]
BTW it seems its only a String Why is this needed Cause it does not seem to be sent to the server, it seems more of a client thing that would block screen sharing. Do you have anther reason to have this here?

**Comment by LoganDark** [comment]
> BTW it seems its only a String Why is this needed Cause it does not seem to be sent to the server, it seems more of a client thing that would block screen sharing. Do you have anther reason to have this here?

Screen sharing wasn't a concern or a use case when making this. I just included that patch for completeness since branding's purpose is to make all parts of the client believe it's unmodded.

Please don't use this mod for screensharing.

**Comment by fooeyround** [comment]
Found it thx
